### ISSUE TITLE
Streaming issue in 0.109.6

### ISSUE THREAD

**Issue by mclare** [marthoc/kuna#21]
Thanks form a different part of the GTA- hope you're staying safe.

Post update to 0.109.6 of Home Assitant, and aiohttp 3.6.2

Recurring error is
    raise ValueError('Unsupported body type %r' % type(body))
ValueError: Unsupported body type <class 'coroutine'>
2020-05-08 13:50:37 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_response.py", line 567, in body
    self._body = body = payload.PAYLOAD_REGISTRY.get(body)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/payload.py", line 106, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/camera/__init__.py", line 490, in get
    return await self.handle(request, camera)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/camera/__init__.py", line 510, in handle
    return web.Response(body=image, content_type=camera.content_type)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_response.py", line 545, in __init__
    self.body = body
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_response.py", line 569, in body
    raise ValueError('Unsupported body type %r' % type(body))
ValueError: Unsupported body type <class 'coroutine'>
/usr/lib/python3.7/asyncio/base_events.py:1756: RuntimeWarning: coroutine 'KunaCamera.camera_image' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by GuitarSkater** [comment]
Can confirm, I have the same issue. It seems to be polling SOME data (streaming/recording status) but no video display.

**Comment by JuliusLedoux** [comment]
I have the same issue. Since version  0.109.6 not streaming and also the switch sensor does not work.
The recordings are still being saved locally.

**Comment by GuitarSkater** [comment]
Just tried the version 0.110.0 beta and it's still messed up

**Comment by JuliusLedoux** [comment]
I did try version 0.110 too. Same result.
