### ISSUE TITLE
Logged warning about `does not support requesting width and height`

### ISSUE THREAD

**Issue by kevin-david** [marthoc/kuna#40]
Doesn't seem to affect anything, like the previous issue I just filed, but figured it was worth reporting as well

```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:502
Integration: Camera (documentation, issues)
First occurred: 8:02:35 PM (3 occurrences)
Last logged: 8:02:35 PM

The camera entity camera.basement_camera does not support requesting width and height, please open an issue with the integration author
The camera entity camera.front_door_camera does not support requesting width and height, please open an issue with the integration author
The camera entity camera.deck_door_camera does not support requesting width and height, please open an issue with the integration author
```

**Comment by ImSorryButWho** [comment]
It appears that this broke image previews on the dashboard with 2022.04:

```
Logger: aiohttp.server
Source: components/camera/__init__.py:163
First occurred: 1:48:45 PM (2 occurrences)
Last logged: 1:49:36 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 724, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 742, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 163, in _async_get_image
    if image_bytes := await camera.async_camera_image(
TypeError: async_camera_image() got an unexpected keyword argument 'width'
```

**Comment by kevin-david** [comment]
@ImSorryButWho [and anyone else] - I fixed this in my fork here: https://github.com/kevin-david/kuna/commit/77163ecd057644ce647907251a2fc7937c94cad9
